# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a10b8c296fc0b0916223b14e8c88e3202d6430d29a352543757b12ab03ea16043f13bd1ab68d06bd810e820fb9e65bdf665b35b731587037b8cf606a7a18e22a
  # This is the space ID. A space is like a project folder in Contentful terms
  contentful_space_id: 'developer_bookshelf'

  # This is the access token for this space. Normally you get both ID and the token in the Contentful web app
  contentful_access_token: '0b7f6x59a0'

test:
  secret_key_base: d5b414f3ec7a25f61559aafa1fd5448d8a0024ab3e6142721cbb390516e0922f9e1290d6d84522bbd811118085d3f9a67591143f596cc863885c2e743783084d

# Do not keep production secrets in the repository,
# instead read values from the environment.
qa:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  rollbar_key: <%= ENV['ROLLBAR_KEY'] %>
  newrelic_key: <%= ENV['NEW_RELIC_KEY'] %>

  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_auth: <%= ENV['SMTP_AUTH'] %>


staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  rollbar_key: <%= ENV['ROLLBAR_KEY'] %>
  newrelic_key: <%= ENV['NEW_RELIC_KEY'] %>

  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_auth: <%= ENV['SMTP_AUTH'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_key: <%= ENV['AWS_KEY'] %>
  aws_secret: <%= ENV['AWS_SECRET'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>
  rollbar_key: <%= ENV['ROLLBAR_KEY'] %>
  newrelic_key: <%= ENV['NEW_RELIC_KEY'] %>

  smtp_user_name: <%= ENV['SMTP_USER_NAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_address: <%= ENV['SMTP_ADDRESS'] %>
  smtp_domain: <%= ENV['SMTP_DOMAIN'] %>
  smtp_port: <%= ENV['SMTP_PORT'] %>
  smtp_auth: <%= ENV['SMTP_AUTH'] %>
